name: CI Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.2"
          enable-cache: true

      - name: Install Python 3.11
        run: uv python install 3.11

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Ruff linter
        run: |
          uv run ruff check .

      - name: Run tests with coverage
        run: |
          uv run pytest