name: CI Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.3/install.sh | sh

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Ruff linter
        run: |
          uv run ruff check .